### ISSUE TITLE
Send a distinct UserAgent with ACME HTTP requests

### ISSUE THREAD

**Issue by cpu** [aptise/peter_sslers#1]
The current ACME draft promoted sending a user-agent as a MUST (previously it was a SHOULD):

>   ACME clients MUST send a User-Agent header, in accordance with
>   [RFC7231].  This header SHOULD include the name and version of the
>   ACME software in addition to the name and version of the underlying
>   HTTP client software.

It doesn't look like `peter_sslers` sends a custom User-Agent presently (though I admit I only skimmed the codebase quickly).

Would you please consider adding a custom User-Agent header to your project? It is extremely helpful for ACME server operators when diagnosing problems using server-side request logs.

Thanks!

**Comment by jvanasco** [comment]
Thanks for pointing this out. It currently *does not* and should.  I'll handle this ASAP.

The `lib/acme_v1.py` file is just a fork off an old version of acme-tiny, which didn't not follow that practice back then (they do now).

**Comment by jvanasco** [comment]
Fixed https://github.com/aptise/peter_sslers/blob/5117f34659d35d53de813e217282edc5b8783ba7/peter_sslers/lib/acme_v1.py#L51-L60

**Comment by cpu** [comment]
@jvanasco Thanks for the quick turnaround! :racehorse: :trophy:
